# Docker Compose configuration for PostgreSQL database service
#
# Services:
#   postgres: PostgreSQL database instance
#     - Uses postgres:13 image
#     - Creates database 'my_store'
#     - Creates user 'wally' with password 'wally'
#     - Exposes port 5432
#     - Persists data in ./postgres_data directory
#
# Usage:
#   docker-compose up    # Start the database
#   docker-compose down  # Stop the database

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=wally
      - POSTGRES_PASSWORD=wally
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.compose
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80


################# GUI ######################
# http://localhost:5050/

################# TERMINAL ####################
# docker-compose exec postgres bash  ---> Connect DB
# psql -h localhost -d my_store - U wally  ---> Connect via terminal
# visualize tables  ---> \d+


