# Docker Compose configuration for PostgreSQL database service
#
# Services:
#   postgres: PostgreSQL database instance
#     - Uses postgres:13 image
#     - Creates database 'my_store'
#     - Creates user 'wally' with password 'wally'
#     - Exposes port 5432
#     - Persists data in ./postgres_data directory
#
# - pgAdmin: Web-based PostgreSQL admin tool
#   - Environment variables for admin login credentials
#   - Web interface accessible on port 5050
#   - Uses dpage/pgadmin4 image
#
# Usage:
#   docker-compose up    # Start the database
#   docker-compose down  # Stop the database

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=wally
      - POSTGRES_PASSWORD=wally
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.compose
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80

  mysql:
    image: mysql:5
    environment:
      - MYSQL_DATABASE=my_store
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_USER=wally
      - MYSQL_ROOT_PASSWORD=root
      - PMA_HOST=mysql
    ports:
      - 8080:80


################# GUI ######################
# http://localhost:5050/

################# TERMINAL ####################
# docker-compose exec postgres bash  ---> Connect DB with bash
# psql -h localhost -d my_store - U wally  ---> Connect via terminal
# visualize tables  ---> \d+


